branch-defaults:
  development:
    environment: uname-development
  master:
    environment: uname-production
environment-defaults:
  uname-development:
    branch: null
    repository: null
global:
  application_name: uname
  branch: null
  default_ec2_keyname: ashleyelaine_keypair
  default_platform: Python 3.6
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
