# Generated by Django 2.1.3 on 2018-11-21 23:56

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True)),
                ('content', wagtail.core.fields.StreamField([('content_block', wagtail.core.blocks.StructBlock([('content', wagtail.core.blocks.RichTextBlock())])), ('sub_heading_block', wagtail.core.blocks.StructBlock([('sub_heading', wagtail.core.blocks.TextBlock(required=True))])), ('cta_block', wagtail.core.blocks.StructBlock([('link', wagtail.core.blocks.CharBlock()), ('link_text', wagtail.core.blocks.CharBlock()), ('target', wagtail.core.blocks.ChoiceBlock(blank=True, choices=[('_self', 'Same Window'), ('_blank', 'New Window')], help_text='Default is Same Window', required=False))]))], blank=True)),
            ],
        ),
    ]
