# Generated by Django 2.1.7 on 2019-03-24 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faqpage',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='FaqPage',
        ),
    ]
