# Generated by Django 2.1.7 on 2019-03-24 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20190324_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postpagetag',
            name='content_object',
        ),
        migrations.RemoveField(
            model_name='postpagetag',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='postpage',
            name='tags',
        ),
        migrations.DeleteModel(
            name='PostPageTag',
        ),
    ]
