# Generated by Django 2.1.7 on 2019-04-03 21:48

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20190403_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basepage',
            name='page_content',
            field=wagtail.core.fields.StreamField([('sub_heading_block', wagtail.core.blocks.StructBlock([('sub_heading', wagtail.core.blocks.TextBlock(required=True))])), ('content_block', wagtail.core.blocks.StructBlock([('content', wagtail.core.blocks.RichTextBlock())])), ('cta_block', wagtail.core.blocks.StructBlock([('link', wagtail.core.blocks.CharBlock()), ('link_text', wagtail.core.blocks.CharBlock()), ('target', wagtail.core.blocks.ChoiceBlock(blank=True, choices=[('_self', 'Same Window'), ('_blank', 'New Window')], help_text='Default is Same Window', required=False))])), ('code_block', wagtail.core.blocks.StructBlock([('code', wagtail.core.blocks.StructBlock([('language', wagtail.core.blocks.ChoiceBlock(choices=[('css', 'CSS'), ('html', 'HTML'), ('javascript', 'Javascript'), ('json', 'JSON'), ('python', 'Python'), ('scss', 'SCSS')], help_text='Coding language', identifier='language', label='Language')), ('code', wagtail.core.blocks.TextBlock(identifier='code', label='Code'))], label='Code'))])), ('html_block', wagtail.core.blocks.StructBlock([('html', wagtail.core.blocks.TextBlock(classname='code', required=True))]))], blank=True),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='page_content',
            field=wagtail.core.fields.StreamField([('sub_heading_block', wagtail.core.blocks.StructBlock([('sub_heading', wagtail.core.blocks.TextBlock(required=True))])), ('content_block', wagtail.core.blocks.StructBlock([('content', wagtail.core.blocks.RichTextBlock())])), ('cta_block', wagtail.core.blocks.StructBlock([('link', wagtail.core.blocks.CharBlock()), ('link_text', wagtail.core.blocks.CharBlock()), ('target', wagtail.core.blocks.ChoiceBlock(blank=True, choices=[('_self', 'Same Window'), ('_blank', 'New Window')], help_text='Default is Same Window', required=False))])), ('code_block', wagtail.core.blocks.StructBlock([('code', wagtail.core.blocks.StructBlock([('language', wagtail.core.blocks.ChoiceBlock(choices=[('css', 'CSS'), ('html', 'HTML'), ('javascript', 'Javascript'), ('json', 'JSON'), ('python', 'Python'), ('scss', 'SCSS')], help_text='Coding language', identifier='language', label='Language')), ('code', wagtail.core.blocks.TextBlock(identifier='code', label='Code'))], label='Code'))])), ('html_block', wagtail.core.blocks.StructBlock([('html', wagtail.core.blocks.TextBlock(classname='code', required=True))]))], blank=True),
        ),
        migrations.AlterField(
            model_name='formpage',
            name='page_content',
            field=wagtail.core.fields.StreamField([('sub_heading_block', wagtail.core.blocks.StructBlock([('sub_heading', wagtail.core.blocks.TextBlock(required=True))])), ('content_block', wagtail.core.blocks.StructBlock([('content', wagtail.core.blocks.RichTextBlock())])), ('cta_block', wagtail.core.blocks.StructBlock([('link', wagtail.core.blocks.CharBlock()), ('link_text', wagtail.core.blocks.CharBlock()), ('target', wagtail.core.blocks.ChoiceBlock(blank=True, choices=[('_self', 'Same Window'), ('_blank', 'New Window')], help_text='Default is Same Window', required=False))])), ('code_block', wagtail.core.blocks.StructBlock([('code', wagtail.core.blocks.StructBlock([('language', wagtail.core.blocks.ChoiceBlock(choices=[('css', 'CSS'), ('html', 'HTML'), ('javascript', 'Javascript'), ('json', 'JSON'), ('python', 'Python'), ('scss', 'SCSS')], help_text='Coding language', identifier='language', label='Language')), ('code', wagtail.core.blocks.TextBlock(identifier='code', label='Code'))], label='Code'))])), ('html_block', wagtail.core.blocks.StructBlock([('html', wagtail.core.blocks.TextBlock(classname='code', required=True))]))], blank=True),
        ),
        migrations.AlterField(
            model_name='postpage',
            name='page_content',
            field=wagtail.core.fields.StreamField([('sub_heading_block', wagtail.core.blocks.StructBlock([('sub_heading', wagtail.core.blocks.TextBlock(required=True))])), ('content_block', wagtail.core.blocks.StructBlock([('content', wagtail.core.blocks.RichTextBlock())])), ('cta_block', wagtail.core.blocks.StructBlock([('link', wagtail.core.blocks.CharBlock()), ('link_text', wagtail.core.blocks.CharBlock()), ('target', wagtail.core.blocks.ChoiceBlock(blank=True, choices=[('_self', 'Same Window'), ('_blank', 'New Window')], help_text='Default is Same Window', required=False))])), ('code_block', wagtail.core.blocks.StructBlock([('code', wagtail.core.blocks.StructBlock([('language', wagtail.core.blocks.ChoiceBlock(choices=[('css', 'CSS'), ('html', 'HTML'), ('javascript', 'Javascript'), ('json', 'JSON'), ('python', 'Python'), ('scss', 'SCSS')], help_text='Coding language', identifier='language', label='Language')), ('code', wagtail.core.blocks.TextBlock(identifier='code', label='Code'))], label='Code'))])), ('html_block', wagtail.core.blocks.StructBlock([('html', wagtail.core.blocks.TextBlock(classname='code', required=True))]))], blank=True),
        ),
    ]
