# Generated by Django 2.1.7 on 2019-04-16 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20190403_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='logo_sub_text',
            field=models.CharField(blank=True, help_text='Add logo sub text.', max_length=255, null=True),
        ),
    ]
